name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Build/Push image
        run: |
          make docker-build
          make docker-push USER=artarts36 TOKEN=${{ secrets.GITHUB_TOKEN }}

      - if: ${{ failure() }}
        name: Send notification about failure build
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ğŸ”» Build failed on commit "${{ github.event.head_commit.message }}" by ${{ github.event.head_commit.author.username }}
            
            ğŸ”— Commit url: ${{ github.event.head_commit.url }}
            
            ğŸŒ Url to failed job: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  deploy:
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: nerd4ever/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          user: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          command: ${{ secrets.PROD_DEPLOY_COMMAND }}

      - if: ${{ failure() }}
        name: Send notification about failure build
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ğŸ”» Deploy failed on commit "${{ github.event.head_commit.message }}" by ${{ github.event.head_commit.author.username }}

            ğŸ”— Commit url: ${{ github.event.head_commit.url }}

            ğŸŒ Url to failed job: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - if: ${{ success() }}
        name: Send notification about failure build
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ğŸ’š Deploy succeed on commit "${{ github.event.head_commit.message }}" by ${{ github.event.head_commit.author.username }}
            â¡ï¸ See new mr-linter.dev
